package com.linkchat.application.owner;
import com.linkchat.application.FileStorageService; import com.linkchat.application.exception.*; import com.linkchat.domain.model.*; import com.linkchat.domain.repository.AccountRepository; import com.linkchat.infrastructure.persistence.OwnerImageRepositoryFacade;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import java.math.BigDecimal; import java.util.*;
@Service public class OwnerProfileService {
 private final AccountRepository accounts; private final OwnerImageRepositoryFacade images; private final FileStorageService storage;
 public OwnerProfileService(AccountRepository a,OwnerImageRepositoryFacade i,FileStorageService s){accounts=a;images=i;storage=s;}
 @Transactional(readOnly=true) public ProfileView profile(String subject){return view(owner(subject));}
 @Transactional public ProfileView update(String subject,BigDecimal price,List<MultipartFile> files,boolean replaceImages){Account a=owner(subject);if(price==null||price.compareTo(new BigDecimal("25.00"))<0)throw new BusinessRuleException("Minimum chat price is R25.00");if(price.scale()>2)price=price.setScale(2,java.math.RoundingMode.HALF_UP);a.setChatPrice(price);accounts.save(a);if(replaceImages)images.deleteByOwnerId(a.getId());if(files!=null){long count=files.stream().filter(f->f!=null&&!f.isEmpty()).count();if(count>6)throw new BusinessRuleException("Maximum 6 profile images");for(MultipartFile f:files){if(f==null||f.isEmpty())continue;if(f.getContentType()==null||!f.getContentType().startsWith("image/"))throw new BusinessRuleException("Only image files are allowed");String key=storage.store(f);images.save(new OwnerImage(a.getId(),key,f.getOriginalFilename(),f.getContentType()));}}return view(a);}
 @Transactional(readOnly=true) public ProfileView publicProfile(String code){return view(accounts.findByInviteCode(code).orElseThrow(()->new ResourceNotFoundException("Invite link not found")));}
 private Account owner(String s){return accounts.findByAuthSubject(s).orElseThrow(()->new ResourceNotFoundException("Owner profile not created yet"));}
 private ProfileView view(Account a){return new ProfileView(a.getId(),a.getDisplayName(),a.getInviteCode(),a.getChatPrice(),images.findByOwnerId(a.getId()).stream().map(x->"/api/images/"+x.getStorageKey()).toList());}
 public record ProfileView(UUID ownerId,String displayName,String inviteCode,BigDecimal chatPrice,List<String> imageUrls){}
}